# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 04:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0003_course_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='reg_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
