# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0004_auto_20171105_0445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_id',
        ),
    ]
