# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 01:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0005_remove_course_course_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='ExamGrade',
            new_name='QuizGrade',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='choice',
            name='isAnswer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='reg_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='frquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnApp.Quiz'),
        ),
        migrations.AlterField(
            model_name='mcquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnApp.Quiz'),
        ),
        migrations.AlterField(
            model_name='quizgrade',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='learnApp.Quiz'),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learnApp.Course'),
        ),
    ]
