# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0006_auto_20171106_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonparts',
            name='lesson',
        ),
        migrations.RenameField(
            model_name='mcquestion',
            old_name='exam',
            new_name='quiz',
        ),
        migrations.AddField(
            model_name='lesson',
            name='info',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='LessonParts',
        ),
    ]
