# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0007_auto_20171106_0450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizgrade',
            name='exam',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='quizgrade',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learnApp.Quiz'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='info',
            field=tinymce.models.HTMLField(),
        ),
    ]
