# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learnApp', '0008_auto_20171120_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgrade',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learnApp.Course'),
        ),
    ]
